language: android
jdk:
    - oraclejdk7
android:
  components:
    - build-tools-22.0.1
    - android-22
    - extra-android-support
    - extra-android-m2repository
  licenses:
    - '.+'
script:
    - ./gradlew clean assemble check
